linters:
  enable:
    - gosimple
    - typecheck
    - govet
    - errcheck
    - staticcheck
    - unused
    - dupl
    - gofmt
    - misspell
    - gocritic
    - bidichk
    - ineffassign
    - revive
    - gofumpt
    - depguard
    - exportloopref
    - goconst
    - promlinter
    - wsl
    - errorlint
    - gomnd
    - nlreturn
    - usestdlibvars
    - varnamelen
    - wrapcheck
  enable-all: false
  disable-all: true
  fast: false

run:
  timeout: 3m

linters-settings:
  gofumpt:
    extra-rules: true
    lang-version: "1.20"
