---
server:
  addr: 0.0.0.0:8080
  host: http://localhost:8080
  pprof: false
  root: /
  cert:
  key:
  strict_curves: false
  strict_ciphers: false
  templates:
  errors:
  errors_title: Oops! You're lost

metrics:
  addr: 0.0.0.0:8081
  token:

log:
  level: info
  pretty: true
  color: true
