baseURL = "https://webhippie.github.io/errors/"
languageCode = "en-us"
title = "Errors"
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Default backend for Kubernetes Ingress"
  keywords = "error, pages, kubernetes, ingress"
